#!/usr/bin/env ansible-playbook

# Setup SSH authorized keys on Unifi/EdgeRouter Devices
---

# Setup SSH authorized keys on Unifi/EdgeRouter Devices

- name: "Create persistent local config directory"
  file: 
    path: /config/local
    state: directory

- name: "Copy SSH public key to router"
  copy: 
    src: "{{ ubnt_ssh_authorized_key }}"
    dest: "/config/local/authorized-ssh-key"

- name: "Copy script to load public key into config"
  copy:
    src: load-authorized-key.sh
    dest: /config/local/load-authorized-key.sh
    mode: 0755

- name: "Load SSH public key into config"
  command: /config/local/load-authorized-key.sh
