---
# tasks file for ppouliot.ubnt_platform_mgmt
#

- name: Execute All Unifi Controller Facts
  include_tasks: all_unifi_controller_facts.yml
  when:
    - inventory_hostname == "localhost"
    - unifi_ctrl_facts == True

- name: Load all curated Unifi Code from Git Repositories to /usr/local/src
  include_tasks: git_repositories.yml
  when:
    - inventory_hostname == "localhost"
    - ubnt_community_code == True

- name: Load all curated Unifi Code from Remote files
  include_tasks: remote_files.yml
  when:
    - inventory_hostname == "localhost"
    - ubnt_community_code == True

- name: Build Cloudflared for MIPs
  include_tasks: build_mips_cloudflared.yml
  when:
    - inventory_hostname == "localhost"
