#!/usr/bin/env ansible-playbook
---

- name: Disable Password Authentication for SSH on UBNT Device
  edgeos_command:
    commands: set service ssh disable-password-authentication
  when:
    - ubnt_ssh_password_auth == "False"
    - ansible_connection == "network_cli"

- name: Enable Password Authentication for SSH on UBNT Device
  edgeos_command:
    commands: delete service ssh disable-password-authentication
  when:
    - ubnt_ssh_password_auth == "True"
    - ansible_connection == "network_cli"
