---

# VLAN inter-accessibility for multicast devices.

    - name: "Configure IGMP-PROXY for Muticast across VLAN interfaces
      edgeos_config:
        backup: yes
        lines:
          - edit protocols igmp-proxy
          # In my case the Sonos devices are on VLAN1 or the Main VLAN of the Unifi network configuration
          # It will be configured as the "Downstream" role
          - set interface {{ usg_igmp_proxy_interface }} role downstream
          - set interface {{ usg_igmp_proxy_interface }} threshold 1
          - set interface {{ usg_igmp_proxy_interface }} alt-subnet 0.0.0.0/0
          # I use a seperate VLAN for Private and public VLAN access. 
          # In this case that Will be set as the "Upstream" role
          - set interface {{ usg_igmp_proxy_interface }}.{{ private_wifi_vlan_id }} role upstream 
          - set interface {{ usg_igmp_proxy_interface }}.{{ private_wifi_vlan_id }} threshold 1
          - set interface {{ usg_igmp_proxy_interface }}.{{ private_wifi_vlan_id }} alt-subnet 0.0.0.0/0
        save: yes
      when:
        - ansible_connection == "network_cli"
  
