---

# VLAN inter-accessibility for multicast devices.

    - name: "Configure VLAN inter-accessibility for multicast devices."
      edgeos_config:
        backup: yes
        lines:
          - edit protocols igmp-proxy
          - set interface {{ usg_multicast_interface }}.{{ sonos_vlan_id }} role downstream 
          - set interface {{ usg_multicast_interface }}.{{ sonos_vlan_id }} threshold 1
          - set interface {{ usg_multicast_interface }}.{{ sonos_vlan_id }} alt-subnet 0.0.0.0/0
          - set interface {{ usg_multicast_interface }} role upstream
          - set interface {{ usg_multicast_interface }} threshold 1
          - set interface {{ usg_multicast_interface }} alt-subnet 0.0.0.0/0
        save: yes
      when:
        - ansible_connection == "network_cli"
  
